### PR TITLE
updated all the packages

### LINKED ISSUE #12: Upgrade to Docusaurus 3.x
Need to upgrade most packages in package.json, especially docusaurus to the latest 3.x version. I tried `ncu -u` to upgrade all packages including docusaurus, but there are a lot of latext related errors, which are probably related to  `rehype-katex` and `remark-math`

### PR DESCRIPTION
**Pull request by Niharika0104**
/closes #12 
Hello @soulmachine  I updated all the packages
Can you check and let me know if these meets the requirements on your end?
And while running the `npm run start`  i got many .md file errors.Do you want me to fix those as well?

### CODE REVIEW

**Comment by soulmachine** [comment]
Hi @Niharika0104 , thanks for sending this PR, but `npm run build` is failing if you just simply upgrade all packages. Please read https://github.com/soulmachine/algorithm-essentials/issues/12 , this issue won't be that easy to fix

**Review by soulmachine — CHANGES_REQUESTED** [review]
`npm run build` is failing

**Comment by Niharika0104** [comment]
@soulmachine latex errors in .md files was the reason why build was failing.
I fixed those errors now build is successful
image

**Review by soulmachine — APPROVED** [review]
Great job, `npm run build` succeeds now! Can you go to [this Gitpay webpage](https://gitpay.me/#/task/992) and claim the bounty?

**Comment by Niharika0104** [comment]
@soulmachine The Gitpay is showing a $150 bounty, but it was supposed to be $200. Could you please transfer the funds through an alternative payment method, such as Stripe?

**Comment by alexanmtz** [comment]
@Niharika0104 @soulmachine Alex from Gitpay here. The payment made was $150 on the platform, so you have $150 to claim, and we use Stripe to process the payment. I could see it was an attempt of $200 and didn't work, then there's a successful of $150. And I could see also there's an attempt comment with the value of $200 but we don't support that comment. So the real payment processed was $150. He can always add bounties and you can the $200 agreed. Let me know if you need any help.

The sponsor can add more $50.

**Comment by Niharika0104** [comment]
Thanks @alexanmtz 
In Bank account set up,routing number is being asked and I don't know what the routing number is..I tried googling it and some sites say that it's something specific to the bank and some sites say it's something specific to the user bank account.I don't know and I'm scared of entering something wrong.Here in India, we have IFSC code to identify banks.

**Comment by soulmachine** [comment]
@Niharika0104 I've added $50 on Gitpay and the total bounty is $200 now, feel free to claim it! Thanks again for your great job!

**Comment by Niharika0104** [comment]
@soulmachine Thank you so much!

**Comment by Niharika0104** [comment]
@soulmachine Can you please close the issue ?
It's a mandatory step for claiming the bounty
Thanks again..

**Comment by alexanmtz** [comment]
> Thanks @alexanmtz In Bank account set up,routing number is being asked and I don't know what the routing number is..I tried googling it and some sites say that it's something specific to the bank and some sites say it's something specific to the user bank account.I don't know and I'm scared of entering something wrong.Here in India, we have IFSC code to identify banks.

Hey @Niharika0104 we can figure out how to register your Bank Account because we do support transfers to India.

For your case, you should fill following these requirements:
_Branch IFSC Code: The Indian Financial System Code of your bank branch.
Bank Account Number: Your account number._

Let me know if it works and you can contact me at alexandre@gitpay.me or joining our Slack channel: 
https://gitpay-workspace.slack.com/join/shared_invite/zt-1ru4j0duc-mOPFRxkhRyMgavlGdlghmw

**Pull request merged**
